const SAFE_TIMESTAMP_SOURCE = '\\d{4}-\\d{2}-\\d{2}T\\d{2}-\\d{2}-\\d{2}-\\d{3}Z';
const GENERATED_TEMP_SOURCE = 'tmp-\\d+-\\d+-\\d+';

export type LegacyLogbookArtifactKind = 'snapshot' | 'journal' | 'metadata';

export interface LegacyLogbookArtifactDescriptor {
  kind: LegacyLogbookArtifactKind;
}

export const LEGACY_RETENTION_MS = 30 * 24 * 60 * 60 * 1000;
export const LEGACY_DIRECTORY_NAME = 'legacy';
export const LEGACY_UNRECOVERABLE_NAME = 'unrecoverable-original.adi';

export const OBSOLETE_RECOVERY_TEMP_NAMES = new Set([
  'rewrite.tmp',
  'last-good.tmp',
  'manifest.json.tmp',
  'operation.lock',
]);

export const LEGACY_RECOVERY_DATA_NAMES = new Set([
  'last-good.adi',
  'tail-fragment.bin',
  'manifest.json',
]);

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function matchesGeneratedCopies(name: string, coreName: string, allowArchive: boolean): boolean {
  const core = escapeRegExp(coreName);
  const directCopy = new RegExp(
    `^${core}(?:\\.bak\\.[123]|\\.${GENERATED_TEMP_SOURCE}|\\.corrupt-${SAFE_TIMESTAMP_SOURCE}(?:\\.${GENERATED_TEMP_SOURCE})?)?$`,
  );
  if (directCopy.test(name)) return true;
  if (!allowArchive) return false;

  return new RegExp(
    `^${core}\\.${SAFE_TIMESTAMP_SOURCE}(?:\\.bak\\.[123]|\\.${GENERATED_TEMP_SOURCE}|\\.corrupt-${SAFE_TIMESTAMP_SOURCE}(?:\\.${GENERATED_TEMP_SOURCE})?)?$`,
  ).test(name);
}

/**
 * Classifies only names generated by the two retired logbook persistence
 * generations. The caller must already know the exact formal ADIF basename.
 */
export function classifyLegacyLogbookArtifactName(
  mainBasename: string,
  name: string,
): LegacyLogbookArtifactDescriptor | null {
  if (!/\.adi$/i.test(mainBasename)) return null;

  const escapedMain = escapeRegExp(mainBasename);
  if (new RegExp(`^${escapedMain}\\.bak\\.[123]$`).test(name)
    || new RegExp(`^${escapedMain}\\.${GENERATED_TEMP_SOURCE}$`).test(name)
    || new RegExp(
      `^${escapedMain}\\.corrupt-${SAFE_TIMESTAMP_SOURCE}(?:\\.${GENERATED_TEMP_SOURCE})?$`,
    ).test(name)) {
    return { kind: 'snapshot' };
  }

  const stem = mainBasename.replace(/\.adi$/i, '');
  for (const prefix of [stem, mainBasename]) {
    if (matchesGeneratedCopies(name, `${prefix}.journal.jsonl`, true)) {
      return { kind: 'journal' };
    }
    if (matchesGeneratedCopies(name, `${prefix}.meta.json`, false)) {
      return { kind: 'metadata' };
    }
  }

  return null;
}

/** Infers a missing formal filename only when the whole artifact name matches. */
export function inferLegacyMainBasename(name: string): string | null {
  const snapshot = /^(.+\.adi)\.(?:bak\.[123]|tmp-\d+-\d+-\d+|corrupt-\d{4}-)/.exec(name);
  if (snapshot && classifyLegacyLogbookArtifactName(snapshot[1]!, name)) {
    return snapshot[1]!;
  }

  for (const marker of ['.journal.jsonl', '.meta.json']) {
    const markerAt = name.indexOf(marker);
    if (markerAt <= 0) continue;
    const prefix = name.slice(0, markerAt);
    const mainBasename = /\.adi$/i.test(prefix) ? prefix : `${prefix}.adi`;
    if (classifyLegacyLogbookArtifactName(mainBasename, name)) return mainBasename;
  }
  return null;
}

export function isKnownQuarantinedName(mainBasename: string, name: string): boolean {
  return LEGACY_RECOVERY_DATA_NAMES.has(name)
    || classifyLegacyLogbookArtifactName(mainBasename, name) !== null;
}
