import { afterEach, describe, expect, it, vi } from 'vitest';

import { QRZService } from '../QRZService.js';
import type { QRZConfig } from '@tx5dr/contracts';

const baseConfig: QRZConfig = {
  apiKey: 'test-api-key',
  autoUploadQSO: false,
};

function createAdifRecord(logId: number): string {
  const callsign = `BG${(logId % 9) + 1}AAA`;
  const qsoDate = '20260401';
  const hour = String(Math.floor((logId % 1440) / 60)).padStart(2, '0');
  const minute = String(logId % 60).padStart(2, '0');
  const timeOn = `${hour}${minute}00`;
  const freq = '7.074000';

  return [
    `<app_qrzlog_logid:${String(logId).length}>${logId}`,
    `<call:${callsign.length}>${callsign}`,
    `<qso_date:8>${qsoDate}`,
    `<time_on:6>${timeOn}`,
    `<freq:${freq.length}>${freq}`,
    '<mode:3>FT8',
    '<eor>',
  ].join('');
}

function createAdifPage(startLogId: number, count: number): string {
  const records = Array.from({ length: count }, (_value, index) => createAdifRecord(startLogId + index)).join('');
  return `Generated by QRZ\n<eoh>\n${records}`;
}

function createTimeoutError(): Error {
  const error = new Error('The operation was aborted due to timeout');
  error.name = 'TimeoutError';
  return error;
}

describe('QRZService', () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
  });

  it('parses nested STATUS data returned through DATA field', async () => {
    const service = new QRZService(baseConfig);
    const fetchMock = vi.fn().mockResolvedValue(
      new Response('RESULT=OK&DATA=CALLSIGN=BG5DRB&COUNT=3', {
        status: 200,
        statusText: 'OK',
      })
    );

    vi.stubGlobal('fetch', fetchMock);

    const result = await service.testConnection();

    expect(result).toEqual({
      success: true,
      message: 'Connection successful',
      callsign: 'BG5DRB',
      logbookCount: 3,
    });
  });

  it('downloads QRZ pages from ADIF response and advances AFTERLOGID', async () => {
    const service = new QRZService(baseConfig);
    const fetchMock = vi.fn()
      .mockResolvedValueOnce(new Response(`RESULT=OK&COUNT=252&ADIF=${createAdifPage(1, 250)}`, {
        status: 200,
        statusText: 'OK',
      }))
      .mockResolvedValueOnce(new Response(`RESULT=OK&COUNT=252&ADIF=${createAdifPage(251, 2)}`, {
        status: 200,
        statusText: 'OK',
      }));

    vi.stubGlobal('fetch', fetchMock);

    const records = await service.downloadQSOs();

    expect(records).toHaveLength(252);
    expect(fetchMock).toHaveBeenCalledTimes(2);

    const firstBody = decodeURIComponent(String(fetchMock.mock.calls[0]?.[1]?.body ?? ''));
    const secondBody = decodeURIComponent(String(fetchMock.mock.calls[1]?.[1]?.body ?? ''));

    expect(firstBody).toContain('ACTION=FETCH');
    expect(firstBody).toContain('OPTION=TYPE:ADIF,MAX:250,AFTERLOGID:0');
    expect(secondBody).toContain('OPTION=TYPE:ADIF,MAX:250,AFTERLOGID:251');
  });

  it('builds BETWEEN option without legacy spaces in FETCH requests', async () => {
    const service = new QRZService(baseConfig);
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(`RESULT=OK&COUNT=1&ADIF=${createAdifPage(10, 1)}`, {
        status: 200,
        statusText: 'OK',
      })
    );

    vi.stubGlobal('fetch', fetchMock);

    const records = await service.downloadQSOs({
      startDate: '2026-04-01',
      endDate: '2026-04-30',
    });

    expect(records).toHaveLength(1);

    const requestBody = decodeURIComponent(String(fetchMock.mock.calls[0]?.[1]?.body ?? ''));
    expect(requestBody).toContain('OPTION=TYPE:ADIF,MAX:250,AFTERLOGID:0,BETWEEN:2026-04-01+2026-04-30');
    expect(requestBody).not.toContain(' 00:00:00');
  });

  it('maps TimeoutError to a readable connection timeout message', async () => {
    const service = new QRZService(baseConfig);
    const fetchMock = vi.fn().mockRejectedValue(createTimeoutError());

    vi.stubGlobal('fetch', fetchMock);

    await expect(service.downloadQSOs()).rejects.toThrow(
      'Connection timeout: QRZ server response too slow, check network connection'
    );
  });
});
